import kfp
from kfp import dsl

from components import generate_data, process_data


@dsl.pipeline(
    name="Basic two-step pipeline",
    description="Generate a small dataset, then process it and log metrics.",
)
def basic_two_step_pipeline(
    num_rows: int = 5,
    prefix: str = "item",
    min_length: int = 0,
):
    """A minimal two-step pipeline mirroring the IBM example I/O patterns.

    Args:
        num_rows (int): Rows generated by step 1.
        prefix (str): Text prefix for generated rows.
        min_length (int): Minimum length filter in step 2.
    """

    # Step 1: Generate dataset
    gen_op = (
        generate_data(
            num_rows=num_rows,
            prefix=prefix,
        ).set_caching_options(enable_caching=False)
    )

    # Step 2: Process dataset (consumes output of step 1)
    _ = (
        process_data(
            input_dataset=gen_op.outputs["generated_dataset"],
            min_length=min_length,
        )
        .after(gen_op)
        .set_caching_options(enable_caching=False)
    )


if __name__ == "__main__":
    kfp.compiler.Compiler().compile(
        pipeline_func=basic_two_step_pipeline,
        package_path=__file__.replace(".py", ".yaml"),
    )


